name: adsff
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.17.6 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  auto_size_text: 3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/adsff/assets/images/line1.svg
    - packages/adsff/assets/images/arrow1.svg
    - packages/adsff/assets/images/ellipse1.png
    - packages/adsff/assets/images/ellipse2.png
    - packages/adsff/assets/images/polygon1.svg
    - packages/adsff/assets/images/star1.svg
    - packages/adsff/assets/images/frame3.svg
